from __future__ import annotations

from typing import Tuple

CLASS_LABELS: Tuple[str, ...] = (
    "person",
    "sofa",
    "armchair",
    "coffee table",
    "side table",
    "dining table",
    "dining chair",
    "bar stool",
    "bookshelf",
    "cabinet",
    "dresser",
    "nightstand",
    "bed",
    "pillow",
    "blanket",
    "wardrobe",
    "mirror",
    "floor lamp",
    "table lamp",
    "ceiling light",
    "television",
    "remote control",
    "game console",
    "sound system",
    "desktop computer",
    "laptop",
    "tablet",
    "smartphone",
    "keyboard",
    "mouse",
    "printer",
    "router",
    "speaker",
    "camera",
    "wall clock",
    "painting",
    "indoor plant",
    "curtain",
    "carpet",
    "laundry basket",
    "vacuum",
    "broom",
    "mop",
    "trash can",
    "recycling bin",
    "kitchen island",
    "refrigerator",
    "oven",
    "microwave",
    "dishwasher",
    "toaster",
    "blender",
    "coffee maker",
    "kettle",
    "cooktop",
    "pot",
    "pan",
    "cutting board",
    "knife block",
    "utensil holder",
    "plate",
    "bowl",
    "mug",
    "wine glass",
    "water bottle",
    "food container",
    "spice rack",
    "mixing bowl",
    "washing machine",
    "dryer",
    "ironing board",
    "iron",
    "toolbox",
    "hammer",
    "screwdriver",
    "wrench",
    "drill",
    "ladder",
    "storage box",
    "pet bed",
    "thermos",
    "cup",
    "glass",
    "plate",
    "bowl",
    "mug",
    "wine glass",
    "water bottle",
    "food container",
    "spice rack",
)


